config/routes.rb
Auth::Application.routes.draw do
  get '/dashboard', to: 'dashboard#static'

  resources :users, only: [:new, :create]
  resources :sessions, only: [:create]

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  get '/about', to: 'welcome#about', as: :about

  root 'welcome#index'

  

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :email, uniqueness: true

	def email=(value)
      value = value.strip.downcase
      write_attribute :email, value
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :current_user?

  private

  def user_logged_in!
    return if current_user.present?
    flash[:alert] = "Please sign in to view that resource!"
    redirect_to login_url
  end

  def sign_in(user)
    session[:user_id] = user.id if user.present?
  end

  def sign_out
    session[:user_id] = nil
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id] if session[:user_id]
  end

  def current_user?
    current_user.present?
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

    before_action :user_logged_in!

	def static
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by email: params[:email].downcase
    if user && user.authenticate(params[:password])
    	session[:user_id] = user.id
        flash[:notice] = "You are signed in!"
    	redirect_to root_url
    else
        flash.now[:alert] = "Invaild email/password."
    	render 'new'
  end
 end

 def destroy
   sign_out
   flash[:notice] = "You are now signed out!"
   redirect_to root_url
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
    	flash[:notice] = "You are now a user!"
      sign_in @user 
    	redirect_to root_url
    else
    	render 'new'
  end
end

  private

  def user_params
  	params.require(:user).permit(
  		:email, :password, :password_confirmation
  		)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
      @users = User.all
	end

	def about
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/static.html.erb
<h1>Dashboard#static</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auth</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user.present? %>
    Welcome <%= current_user.email %>! | <%= link_to 'Sign Out', logout_path %>
  <% else %>
    <%= link_to 'Register', new_user_path %> | <%= link_to 'Sign In', login_path %>
  <% end %>

  <%= notice %>
  <%= alert %>	
  
  <%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Users#new</h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>  	
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>  	
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>  	
  </div>
    <%= f.submit %>
<% end %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>

<%= link_to 'About Us', about_path %>
<%= link_to 'Private Dashboard', dashboard_path %><br>

<% if current_user? %>
 <ul>
   <% @users.each do |user| %>
     <li><%= user.email %></li>
   <% end %>
 </ul>
<% end %>